[package]
name = "AOTviewer"
version = "0.1.0"
edition = "2024"

[dependencies]
proc-macro2 = "1.0.95"
quote = "1.0.40"

syn = "2.0.100"
[lib]
path = "src/macros.rs"
proc-macro = true
[[bin]]
name = "fmt"
path = "src/fmt.rs"
